/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as web3 from '@solana/web3.js'
import * as beet from '@metaplex-foundation/beet'
import * as beetSolana from '@metaplex-foundation/beet-solana'

/**
 * Arguments used to create {@link Comptoir}
 * @category Accounts
 * @category generated
 */
export type ComptoirArgs = {
  fees: number
  feesDestination: web3.PublicKey
  authority: web3.PublicKey
  mint: web3.PublicKey
}

export const comptoirDiscriminator = [33, 70, 255, 164, 49, 5, 149, 215]
/**
 * Holds the data for the {@link Comptoir} Account and provides de/serialization
 * functionality for that data
 *
 * @category Accounts
 * @category generated
 */
export class Comptoir implements ComptoirArgs {
  private constructor(
    readonly fees: number,
    readonly feesDestination: web3.PublicKey,
    readonly authority: web3.PublicKey,
    readonly mint: web3.PublicKey
  ) {}

  /**
   * Creates a {@link Comptoir} instance from the provided args.
   */
  static fromArgs(args: ComptoirArgs) {
    return new Comptoir(
      args.fees,
      args.feesDestination,
      args.authority,
      args.mint
    )
  }

  /**
   * Deserializes the {@link Comptoir} from the data of the provided {@link web3.AccountInfo}.
   * @returns a tuple of the account data and the offset up to which the buffer was read to obtain it.
   */
  static fromAccountInfo(
    accountInfo: web3.AccountInfo<Buffer>,
    offset = 0
  ): [Comptoir, number] {
    return Comptoir.deserialize(accountInfo.data, offset)
  }

  /**
   * Retrieves the account info from the provided address and deserializes
   * the {@link Comptoir} from its data.
   *
   * @throws Error if no account info is found at the address or if deserialization fails
   */
  static async fromAccountAddress(
    connection: web3.Connection,
    address: web3.PublicKey,
    commitmentOrConfig?: web3.Commitment | web3.GetAccountInfoConfig
  ): Promise<Comptoir> {
    const accountInfo = await connection.getAccountInfo(
      address,
      commitmentOrConfig
    )
    if (accountInfo == null) {
      throw new Error(`Unable to find Comptoir account at ${address}`)
    }
    return Comptoir.fromAccountInfo(accountInfo, 0)[0]
  }

  /**
   * Provides a {@link web3.Connection.getProgramAccounts} config builder,
   * to fetch accounts matching filters that can be specified via that builder.
   *
   * @param programId - the program that owns the accounts we are filtering
   */
  static gpaBuilder(
    programId: web3.PublicKey = new web3.PublicKey(
      'EZxFrEd1TBL6A1zzSvcasnR7RyEwRqkLmBjvLsSCaKNc'
    )
  ) {
    return beetSolana.GpaBuilder.fromStruct(programId, comptoirBeet)
  }

  /**
   * Deserializes the {@link Comptoir} from the provided data Buffer.
   * @returns a tuple of the account data and the offset up to which the buffer was read to obtain it.
   */
  static deserialize(buf: Buffer, offset = 0): [Comptoir, number] {
    return comptoirBeet.deserialize(buf, offset)
  }

  /**
   * Serializes the {@link Comptoir} into a Buffer.
   * @returns a tuple of the created Buffer and the offset up to which the buffer was written to store it.
   */
  serialize(): [Buffer, number] {
    return comptoirBeet.serialize({
      accountDiscriminator: comptoirDiscriminator,
      ...this,
    })
  }

  /**
   * Returns the byteSize of a {@link Buffer} holding the serialized data of
   * {@link Comptoir}
   */
  static get byteSize() {
    return comptoirBeet.byteSize
  }

  /**
   * Fetches the minimum balance needed to exempt an account holding
   * {@link Comptoir} data from rent
   *
   * @param connection used to retrieve the rent exemption information
   */
  static async getMinimumBalanceForRentExemption(
    connection: web3.Connection,
    commitment?: web3.Commitment
  ): Promise<number> {
    return connection.getMinimumBalanceForRentExemption(
      Comptoir.byteSize,
      commitment
    )
  }

  /**
   * Determines if the provided {@link Buffer} has the correct byte size to
   * hold {@link Comptoir} data.
   */
  static hasCorrectByteSize(buf: Buffer, offset = 0) {
    return buf.byteLength - offset === Comptoir.byteSize
  }

  /**
   * Returns a readable version of {@link Comptoir} properties
   * and can be used to convert to JSON and/or logging
   */
  pretty() {
    return {
      fees: this.fees,
      feesDestination: this.feesDestination.toBase58(),
      authority: this.authority.toBase58(),
      mint: this.mint.toBase58(),
    }
  }
}

/**
 * @category Accounts
 * @category generated
 */
export const comptoirBeet = new beet.BeetStruct<
  Comptoir,
  ComptoirArgs & {
    accountDiscriminator: number[] /* size: 8 */
  }
>(
  [
    ['accountDiscriminator', beet.uniformFixedSizeArray(beet.u8, 8)],
    ['fees', beet.u16],
    ['feesDestination', beetSolana.publicKey],
    ['authority', beetSolana.publicKey],
    ['mint', beetSolana.publicKey],
  ],
  Comptoir.fromArgs,
  'Comptoir'
)
