[features]
skip-lint = false

[programs.localnet]
comptoir = "EZxFrEd1TBL6A1zzSvcasnR7RyEwRqkLmBjvLsSCaKNc"


[registry]
url = "http://127.0.0.1:8899"

# [registry]
# url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/daniel/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
client = "yarn run ts-node client/*.ts"
example = "yarn run ts-node packages/comptoirjs/examples/complete_workflow.ts"

[[test.genesis]]
address = "EZxFrEd1TBL6A1zzSvcasnR7RyEwRqkLmBjvLsSCaKNc"
program = "./deps/metadata.so"
