[features]
seeds = false
skip-lint = false

[programs.localnet]
comptoir = "FY4tLSXn95o5YuecY3sAfPCoPk9ZSs2cvFa9HiHYPFgy"

[programs.devnet]
comptoir = "FY4tLSXn95o5YuecY3sAfPCoPk9ZSs2cvFa9HiHYPFgy"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
# cluster = "devnet"
wallet = "/home/daniel/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -t 1000000 tests/**/*.ts"
client = "yarn run ts-node client/*.ts"
example-wf = "yarn run ts-node comptoirjs/examples/complete_workflow.ts"
